version: '3'
services:
  api:
    image: 387624221254.dkr.ecr.ap-southeast-1.amazonaws.com/toraq-api-v3-php-production:latest
    build:
      dockerfile: deployments/Dockerfile
    env_file:
      - .env.production
    ports:
      - "8000:80"
    networks:
      - app
networks:
  app:
    driver: bridge
